package SERVER_RESTAURANT.MODEL;
// Generated 29-may-2019 16:28:58 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DinnerTable generated by hbm2java
 */
@Entity
@Table(name = "dinner_table", catalog = "RESTAURANT")
public class DinnerTable implements java.io.Serializable {

	private int idTable;
	private String locationTable;
	private Integer numberDinersTable;

	public DinnerTable() {
	}

	public DinnerTable(int idTable) {
		this.idTable = idTable;
	}

	public DinnerTable(int idTable, String locationTable, Integer numberDinersTable) {
		this.idTable = idTable;
		this.locationTable = locationTable;
		this.numberDinersTable = numberDinersTable;
	}

	@Id

	@Column(name = "id_table", unique = true, nullable = false)
	public int getIdTable() {
		return this.idTable;
	}

	public void setIdTable(int idTable) {
		this.idTable = idTable;
	}

	@Column(name = "location_table")
	public String getLocationTable() {
		return this.locationTable;
	}

	public void setLocationTable(String locationTable) {
		this.locationTable = locationTable;
	}

	@Column(name = "number_diners_table")
	public Integer getNumberDinersTable() {
		return this.numberDinersTable;
	}

	public void setNumberDinersTable(Integer numberDinersTable) {
		this.numberDinersTable = numberDinersTable;
	}

}
