package SERVER_RESTAURANT.MODEL;
// Generated 05-jun-2019 4:27:11 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Drink generated by hbm2java
 */
@Entity
@Table(name = "drink", catalog = "RESTAURANT")
public class Drink implements java.io.Serializable {

	private Integer idItemDrink;
	private float price;
	private String nameDrink;
	private int quantityStock;
	private int statusDrink;
	private String descriptionDrink;

	public Drink() {
	}

	public Drink(float price, String nameDrink, int quantityStock, int statusDrink) {
		this.price = price;
		this.nameDrink = nameDrink;
		this.quantityStock = quantityStock;
		this.statusDrink = statusDrink;
	}

	public Drink(float price, String nameDrink, int quantityStock, int statusDrink, String descriptionDrink) {
		this.price = price;
		this.nameDrink = nameDrink;
		this.quantityStock = quantityStock;
		this.statusDrink = statusDrink;
		this.descriptionDrink = descriptionDrink;
	}
	
	public Drink(String nameDrink,float price, int quantityStock, String descriptionDrink) {
		this.price = price;
		this.nameDrink = nameDrink;
		this.quantityStock = quantityStock;
		this.descriptionDrink = descriptionDrink;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_item_drink", unique = true, nullable = false)
	public Integer getIdItemDrink() {
		return this.idItemDrink;
	}

	public void setIdItemDrink(Integer idItemDrink) {
		this.idItemDrink = idItemDrink;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "name_drink", nullable = false)
	public String getNameDrink() {
		return this.nameDrink;
	}

	public void setNameDrink(String nameDrink) {
		this.nameDrink = nameDrink;
	}

	@Column(name = "quantity_stock", nullable = false)
	public int getQuantityStock() {
		return this.quantityStock;
	}

	public void setQuantityStock(int quantityStock) {
		this.quantityStock = quantityStock;
	}

	@Column(name = "status_drink", nullable = false)
	public int getStatusDrink() {
		return this.statusDrink;
	}

	public void setStatusDrink(int statusDrink) {
		this.statusDrink = statusDrink;
	}

	@Column(name = "description_drink")
	public String getDescriptionDrink() {
		return this.descriptionDrink;
	}

	public void setDescriptionDrink(String descriptionDrink) {
		this.descriptionDrink = descriptionDrink;
	}

}
