package SERVER_RESTAURANT.MODEL;
// Generated 29-may-2019 16:28:58 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Drink generated by hbm2java
 */
@Entity
@Table(name = "drink", catalog = "RESTAURANT")
public class Drink implements java.io.Serializable {

	private int idItemDrink;
	private float price;
	private String nameDrink;
	private int quantityStock;
	private int statusDrink;
	private String descriptionDrink;

	public Drink() {
	}

	public Drink(int idItemDrink, float price, String nameDrink, int quantityStock, int statusDrink) {
		this.idItemDrink = idItemDrink;
		this.price = price;
		this.nameDrink = nameDrink;
		this.quantityStock = quantityStock;
		this.statusDrink = statusDrink;
	}

	public Drink(int idItemDrink, float price, String nameDrink, int quantityStock, int statusDrink,
			String descriptionDrink) {
		this.idItemDrink = idItemDrink;
		this.price = price;
		this.nameDrink = nameDrink;
		this.quantityStock = quantityStock;
		this.statusDrink = statusDrink;
		this.descriptionDrink = descriptionDrink;
	}

	@Id

	@Column(name = "id_item_drink", unique = true, nullable = false)
	public int getIdItemDrink() {
		return this.idItemDrink;
	}

	public void setIdItemDrink(int idItemDrink) {
		this.idItemDrink = idItemDrink;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "name_drink", nullable = false)
	public String getNameDrink() {
		return this.nameDrink;
	}

	public void setNameDrink(String nameDrink) {
		this.nameDrink = nameDrink;
	}

	@Column(name = "quantity_stock", nullable = false)
	public int getQuantityStock() {
		return this.quantityStock;
	}

	public void setQuantityStock(int quantityStock) {
		this.quantityStock = quantityStock;
	}

	@Column(name = "status_drink", nullable = false)
	public int getStatusDrink() {
		return this.statusDrink;
	}

	public void setStatusDrink(int statusDrink) {
		this.statusDrink = statusDrink;
	}

	@Column(name = "description_drink")
	public String getDescriptionDrink() {
		return this.descriptionDrink;
	}

	public void setDescriptionDrink(String descriptionDrink) {
		this.descriptionDrink = descriptionDrink;
	}

}
