package SERVER_RESTAURANT.MODEL;
// Generated 29-may-2019 16:28:58 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Hasdrink generated by hbm2java
 */
@Entity
@Table(name = "hasdrink", catalog = "RESTAURANT")
public class Hasdrink implements java.io.Serializable {

    private HasdrinkId id;
    private Integer quantityItem;

    public Hasdrink() {
    }

    public Hasdrink(HasdrinkId id) {
        this.id = id;
    }

    public Hasdrink(HasdrinkId id, Integer quantityItem) {
        this.id = id;
        this.quantityItem = quantityItem;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idTicket", column = @Column(name = "id_ticket", nullable = false))
        ,
			@AttributeOverride(name = "idItemDrink", column = @Column(name = "id_item_drink", nullable = false))})
    public HasdrinkId getId() {
        return this.id;
    }

    public void setId(HasdrinkId id) {
        this.id = id;
    }

    @Column(name = "quantity_item")
    public Integer getQuantityItem() {
        return this.quantityItem;
    }

    public void setQuantityItem(Integer quantityItem) {
        this.quantityItem = quantityItem;
    }

}
