package SERVER_RESTAURANT.MODEL;
// Generated 21-may-2019 12:53:03 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "RESTAURANT")
public class Ticket implements java.io.Serializable {

	private Integer idTicket;
	private Float totalPrice;
	private Integer idTable;

	public Ticket() {
	}

	public Ticket(Float totalPrice, Integer idTable) {
		this.totalPrice = totalPrice;
		this.idTable = idTable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ticket", unique = true, nullable = false)
	public Integer getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(Integer idTicket) {
		this.idTicket = idTicket;
	}

	@Column(name = "total_price", precision = 12, scale = 0)
	public Float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "id_table")
	public Integer getIdTable() {
		return this.idTable;
	}

	public void setIdTable(Integer idTable) {
		this.idTable = idTable;
	}

}
